#!/bin/bash

. config.sh

docker rm $RABBIT_NAME || true

docker run -d \
  --hostname $RABBIT_NAME \
  --name $RABBIT_NAME \
  -p $RABBIT_PORT:5672 \
  -p $RABBIT_MGMT_PORT:15672 \
  -v $PWD/$RABBIT_NAME-mnesia:/var/lib/rabbitmq/mnesia/rabbit@$RABBIT_NAME \
  rabbitmq:3-management
